#!/usr/bin/env bash
set -euo pipefail

REPORT="coverage/gremlins/gremlins.json"
MARKER="<!-- pytest-gremlins-action -->"
THRESHOLD="${INPUT_THRESHOLD}"
PR_NUMBER="${GITHUB_PR_NUMBER}"
REPO="${GITHUB_REPOSITORY}"

# Post/update a comment using the GitHub API
post_comment() {
  local body="$1"
  local existing_id
  existing_id=$(curl -sf \
    -H "Authorization: token ${GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github.v3+json" \
    "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments" \
    | jq -r --arg marker "${MARKER}" '.[] | select(.body | startswith($marker)) | .id' \
    | head -1)

  if [[ -n "${existing_id}" ]] && [[ "${existing_id}" != "null" ]]; then
    curl -sf -X PATCH \
      -H "Authorization: token ${GITHUB_TOKEN}" \
      -H "Accept: application/vnd.github.v3+json" \
      "https://api.github.com/repos/${REPO}/issues/comments/${existing_id}" \
      -d "$(jq -n --arg body "${body}" '{body: $body}')" > /dev/null
    echo "Updated existing PR comment"
  else
    curl -sf -X POST \
      -H "Authorization: token ${GITHUB_TOKEN}" \
      -H "Accept: application/vnd.github.v3+json" \
      "https://api.github.com/repos/${REPO}/issues/${PR_NUMBER}/comments" \
      -d "$(jq -n --arg body "${body}" '{body: $body}')" > /dev/null
    echo "Created new PR comment"
  fi
}

if [[ ! -f "${REPORT}" ]]; then
  BODY="${MARKER}
## Mutation Testing Report

**Score: 100%** (threshold: ${THRESHOLD}%)

No mutations were generated — source code has no mutable statements.

---
*Generated by [pytest-gremlins-action](https://github.com/mikelane/pytest-gremlins-action)*"
  post_comment "${BODY}"
  exit 0
fi

SCORE=$(jq -r '.summary.percentage' "${REPORT}")
ZAPPED=$(jq -r '.summary.zapped' "${REPORT}")
SURVIVED=$(jq -r '.summary.survived' "${REPORT}")
TIMEOUT=$(jq -r '.summary.timeout' "${REPORT}")
PARDONED=$(jq -r '.summary.pardoned' "${REPORT}")
TOTAL=$(jq -r '.summary.total' "${REPORT}")

# Build surviving mutations table (top 20)
SURVIVORS=$(jq -r '
  [.results[] | select(.status == "survived")] | .[0:20] |
  map("| `\(.file_path)` | \(.line_number) | \(.operator) | \(.description) |") |
  join("\n")
' "${REPORT}")

SURVIVED_COUNT=$(jq -r '[.results[] | select(.status == "survived")] | length' "${REPORT}")

# Build comment body
BODY="${MARKER}
## Mutation Testing Report

**Score: ${SCORE}%** (threshold: ${THRESHOLD}%)

| Metric | Count |
|--------|-------|
| Zapped | ${ZAPPED} |
| Survived | ${SURVIVED} |
| Timeout | ${TIMEOUT} |
| Pardoned | ${PARDONED} |
| **Total** | **${TOTAL}** |"

if [[ "${SURVIVED_COUNT}" -gt 0 ]]; then
  BODY="${BODY}

<details>
<summary>Top surviving mutations (${SURVIVED_COUNT})</summary>

| File | Line | Operator | Mutation |
|------|------|----------|----------|
${SURVIVORS}

</details>"
fi

BODY="${BODY}

---
*Generated by [pytest-gremlins-action](https://github.com/mikelane/pytest-gremlins-action)*"

post_comment "${BODY}"
